---
title: "Práctico 2"
author: "Dario Chávez"
date: "`r Sys.Date()`"
output: html_document
---

## Pregunta 2

Elaborad, usando las librerías de gráficos base y qplot (ggplot2), una infografía sobre los 
datos obtenidos. Tal infografía será una reunión de gráficos donde se muestren los 
siguientes detalles: 

### 1. Un histograma con la frecuencia de aparición de los enlaces, pero separado por URLs absolutas (con “http…”) y URLs relativas. 


### 2. Un gráfico de barras indicando la suma de enlaces que apuntan a otros  dominios o servicios (distinto a https://www.mediawiki.org en el caso de ejemplo) vs. la suma de los otros enlaces.

Aquí queremos distinguir enlaces que apuntan a mediawiki versus el resto. 
Sabemos que las URLs relativas ya apuntan dentro, por lo tanto hay que analizar 
las URLs absolutas y comprobar que apunten a https://www.mediawiki.org.


### 3. Un gráfico de tarta (pie chart) indicando los porcentajes de Status de nuestro análisis. 

Por ejemplo, si hay 6 enlaces con status “200” y 4 enlaces con status “404”, la 
tarta mostrará un 60% con la etiqueta “200” y un 40% con la etiqueta “404”. Este 
gráfico lo uniremos a los anteriores. El objetivo final es obtener una imagen que 
recopile los gráficos generados. 
